//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/CarPosUpdateFrame.msg.
//

#ifndef __CARPOSUPDATEFRAME_M_H
#define __CARPOSUPDATEFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class CarPosUpdateFrame;
/**
 * Class generated from <tt>messages/CarPosUpdateFrame.msg:2</tt> by opp_msgtool.
 * <pre>
 * message CarPosUpdateFrame
 * {
 *     int x;
 *     int y;
 * }
 * </pre>
 */
class CarPosUpdateFrame : public ::omnetpp::cMessage
{
  protected:
    int x = 0;
    int y = 0;

  private:
    void copy(const CarPosUpdateFrame& other);

  protected:
    bool operator==(const CarPosUpdateFrame&) = delete;

  public:
    CarPosUpdateFrame(const char *name=nullptr, short kind=0);
    CarPosUpdateFrame(const CarPosUpdateFrame& other);
    virtual ~CarPosUpdateFrame();
    CarPosUpdateFrame& operator=(const CarPosUpdateFrame& other);
    virtual CarPosUpdateFrame *dup() const override {return new CarPosUpdateFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getX() const;
    virtual void setX(int x);

    virtual int getY() const;
    virtual void setY(int y);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CarPosUpdateFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CarPosUpdateFrame& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline CarPosUpdateFrame *fromAnyPtr(any_ptr ptr) { return check_and_cast<CarPosUpdateFrame*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CARPOSUPDATEFRAME_M_H

