//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/CloudFeedbackFrame.msg.
//

#ifndef __CLOUDFEEDBACKFRAME_M_H
#define __CLOUDFEEDBACKFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class CloudFeedbackFrame;
/**
 * Class generated from <tt>messages/CloudFeedbackFrame.msg:2</tt> by opp_msgtool.
 * <pre>
 * message CloudFeedbackFrame
 * {
 *     int source;
 *     int destination;
 *     int hopCount;
 * }
 * </pre>
 */
class CloudFeedbackFrame : public ::omnetpp::cMessage
{
  protected:
    int source = 0;
    int destination = 0;
    int hopCount = 0;

  private:
    void copy(const CloudFeedbackFrame& other);

  protected:
    bool operator==(const CloudFeedbackFrame&) = delete;

  public:
    CloudFeedbackFrame(const char *name=nullptr, short kind=0);
    CloudFeedbackFrame(const CloudFeedbackFrame& other);
    virtual ~CloudFeedbackFrame();
    CloudFeedbackFrame& operator=(const CloudFeedbackFrame& other);
    virtual CloudFeedbackFrame *dup() const override {return new CloudFeedbackFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSource() const;
    virtual void setSource(int source);

    virtual int getDestination() const;
    virtual void setDestination(int destination);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CloudFeedbackFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CloudFeedbackFrame& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline CloudFeedbackFrame *fromAnyPtr(any_ptr ptr) { return check_and_cast<CloudFeedbackFrame*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CLOUDFEEDBACKFRAME_M_H

